
#########################################################################################################
#' IDs mappable by SBGNview
#' @details ID types mappable to glyph IDs in SBGNhub SBGN-ML file collection.
#' @format A list with two elements: A vector of mappable gene ID types (\code{mapped.ids[["gene"]]}), a vector of mappable compound ID types (\code{mapped.ids[["cpd"]]}).
"mapped.ids"

#########################################################################################################
#' Information of collected pathways
#' @details The information of pre-collected pathways and their SBGN-ML file information, such as pathway ID, name, source database, glyph ID types and URLs to the original pathway webpages.
#' @format A data.frame
"pathways.info"

#########################################################################################################
#' Number of pathways collected
#' @details The number of pathways in SBGNhub from each source database. It is calculated from data 'pathways.info'.
#' @format A data.frame
"pathways.stats"

#########################################################################################################
#' Demo SBGNview object
#' @details An example SBGNview object for demo purposes. 
#' This S3 class of objects contains information generated by the SBGNview function.
#' The SBGNview object can be modified by using the "+" binary operator in conjunction with the \code{\link{highlightArcs}}, \code{\link{highlightNodes}}, and \code{\link{highlightPath}} functions. 
#' This mechanism to allow layer-by-layer graph modification is similar to that of ggplot2, a widely used R package for data visualization. 
#' Defining this class as a formal (S4) class will produce an S4 SBGNview object which doesn't work with the binary operator and doesn't allow for layer-by-layer graph modification. 
#' Therefore, we decided to go with the S3 implementation of the SBGNview class since it works well with the binary operator making this 
#' functionality more intuitive and user friendly. 
#' @format A SBGNview S3 class object
"SBGNview.obj"

#########################################################################################################
