
#########################################################################################################
#' IDs mappable by SBGNview
#' @details ID types mappable to glyph IDs in SBGNhub SBGN-ML file collection.
#' @format A list with two elements: A vector of mappable gene ID types (\code{mapped.ids[["gene"]]}), a vector of mappable compound ID types (\code{mapped.ids[["cpd"]]}).
#' @usage data(mapped.ids)
"mapped.ids"

#########################################################################################################
#' Information of collected pathways
#' @details The information of pre-collected pathways and their SBGN-ML file information, such as pathway ID, name, source database, glyph ID types and URLs to the original pathway webpages.
#' @format A data.frame
#' @usage data(pathways.info)
"pathways.info"

#########################################################################################################
#' Number of pathways collected
#' @details The number of pathways in SBGNhub from each source database. It is calculated from data 'pathways.info'.
#' @format A data.frame
#' @usage data(pathways.stats)
"pathways.stats"

#########################################################################################################
#' Demo SBGNview object
#' @details An example SBGNview object for demo purposes. 
#' This S3 class of objects contains information generated by the SBGNview function.
#' The SBGNview object can be modified by using the "+" binary operator in conjunction with the \code{\link{highlightArcs}}, \code{\link{highlightNodes}}, and \code{\link{highlightPath}} functions. 
#' This mechanism to allow layer-by-layer graph modification is similar to that of ggplot2, a widely used R package for data visualization. 
#' Defining this class as a formal (S4) class will produce an S4 SBGNview object which doesn't work with the binary operator and doesn't allow for layer-by-layer graph modification. 
#' Therefore, we decided to go with the S3 implementation of the SBGNview class since it works well with the binary operator making this 
#' functionality more intuitive and user friendly. 
#' 
#' @format A list containing three elements:
#' 
#'           1. data: 
#'              A list contains information for all input SBGN pathways. Each element is a list (e.g. 'P00001') holding information of a single SBGN pathway. The information include parsed information of glyphs, arcs and SBGNview parameters passed to SBGNview function
#'              
#'           2. output.file:
#'              A string of the path to the output file. It is the string set by parameter 'output.file' in function SBGNview.
#'              
#'           3. output.formats:
#'              A character vector specifying the formats of output image files. The vector should be a subset of c('pdf' , 'ps', 'png'). By default the function will always output a svg file.
#' @usage data(SBGNview.obj)
"SBGNview.obj"

#########################################################################################################
#' Mapping tables available in SBGNhub
#' @details A collection of ID mapping table files available in SBGNhub. 
#' If a matching mapping table is available, it will be downloaded from \href{https://github.com/datapplab/SBGNhub/tree/master/data/id.mapping.unique.pair.name}{SBGNhub} github page.
#' @format A matrix
#' @usage data(SBGNhub.id.mapping.tables)
"SBGNhub.id.mapping.tables"

#########################################################################################################
